### ISSUE TITLE
Ability to publish a service with arbitrary interface

### ISSUE THREAD

**Issue by lukaszPulawski** [PayU-Tech/Ratel#25]
Right now a bean annotated with Publish annotation is registered at the registry server with use of the first interface it implements. This is problematic when a class can implement more than one interface.  
This issue is about finding a way to overcome this limitation. A proposal looks like this
```java
@Publish(value=com.domain.MyService)
MyBean implements AnotherService, MyService
```
Subject to investigation and discussion.

**Comment by sentinelt** [comment]
Another proposition:
Annotate an interface with @Service. Then @Publish should register for all annotated interfaces.

**Comment by piotrromanski** [comment]
I believe we should leave api (interfaces) without any ratel specific annotations (contrary to EJB).
I agree with Lukasz. I would also fail deployment if class implements more than one interface and none is  specified in Publish annotation (but what with backward compatibility?). I would also rename "value" property to sth like "endpointInterfaces" or just "interfaces".
