### ISSUE TITLE
Mandatory jboss.bind.address and jboss.bind.port properties

### ISSUE THREAD

**Issue by lukaszPulawski** [PayU-Tech/Ratel#26]
When service is registered, its absolute address is build according to this scheme
http://\<value of property jboss.bind.address\>:\<value of property jboss.bind.port\>/\<dispatcher servlet's context path\>/ratelServices/\<name of service first interface\>
This is specific solution, that assumes that both **jboss.bind.address** and **jboss.bind.port** are set. In the future a more generic solution of generation of the service absolute address will be implemented. This issue is about finding and implementing such solution.

**Comment by pgrela** [comment]
Dedicated property named 'serviceDiscovery.selfAddress' is available.
