### ISSUE TITLE
Default health-check proxy

### ISSUE THREAD

**Issue by lukaszPulawski** [PayU-Tech/Ratel#27]
Ratel service exporters can be decorarted with health check wrapper so that a health-check  call to the service will return apprpriate success response.
This task is about desgning, documenting and implementing appropriate health-check mechanism.

What should be delivered:
- a service wrapper that handles default, dummy  health-check requests with appropriate response.  
- an example client for this mechanism  (separate module?)
- tests in ratel-tests
- documentation on wiki

**Comment by piotrromanski** [comment]
My idea is to add something similar to http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#_writing_custom_healthindicators
The Publish annotation could reference such indicator.

**Comment by lukaszPulawski** [comment]
Good idea, we will do it within issue #41

**Comment by sq3ope** [comment]
Under development.

**Comment by dmuchawiec** [comment]
Add some docs here https://github.com/PayU-Tech/Ratel/wiki/Monitoring
