### ISSUE TITLE
Extensive use of JdkDynamicProxies

### ISSUE THREAD

**Issue by lukaszPulawski** [PayU-Tech/Ratel#45]
Current implementation of Ratel both on client and server side uses many dynamic proxies, e.g.:
com.payu.ratel.client.ClientProxyDecorator.decorateWithMonitoring
com.payu.ratel.client.RatelClientProducer.decorateWithCaching
com.payu.ratel.client.RatelClientProducer.decorateWithRetryPolicy
com.payu.ratel.register.ServiceRegisterPostProcessor.decorateWithMonitoring
com.payu.ratel.proxy.monitoring.ServiceInvocationHandler

It also applies to hand made interceptors, e.g.
com.payu.ratel.client.RatelHessianProxyFactoryBean.invoke

This has negative impact on manageability and performance. Ideally, there should be single proxy on client side and single on server side and all decorators should be implemneted as interceptors injected to the two proxies.  Most probably org.springframework.aop.framework.ProxyFactory should be used for this purpose.

*This issue is about changing the implementation so that the above condition is met*

**Comment by slawekjaranowski** [comment]
PR #59 resolve this issue
