### ISSUE TITLE
Different timeouts for different services

### ISSUE THREAD

**Issue by ynleborg** [PayU-Tech/Ratel#65]
Right now Ratel allows us to ser one timeout globally. This is not sufficient because we have many services and we need different timeouts for them. For example authorization request has to throw timeout after max 1 second, whereas getting transaction list can take up to 30 seconds to complete.

Ideally, there should be a possibility to set timeout on service class and service method level.

**Comment by slawekjaranowski** [comment]
It was resolved by #67
